### ISSUE TITLE
An issue in the "__init__.py" in 'functions' of 'layers'

### ISSUE THREAD

**Issue by oyxhust** [yqyao/SSD_Pytorch#1]
Thanks for your work. I tested your code, and it worked well except one issue in the "__init__.py" in 'functions' of 'layers'.

In this file, there has "from .refine_prior_box import RefinePriorBox". Actually, there are no such files under the 'functions'. Is the 'prior_layer.py' actually the 'refine_prior_box.py'? I remove this sentence, and your code can work when using 'ssd_vgg'. May this be need when using "refined_ssd_vgg".

**Comment by yqyao** [comment]
I am so sorry for it. I forgot to upload this file. I have uploaded this file now  :） @oyxhust

**Comment by yqyao** [comment]
Actually, it's not used in this project. So you can delete this ' from .refine_prior_box import RefinePriorBox'. @oyxhust

**Comment by oyxhust** [comment]
Thanks a lot!
