### ISSUE TITLE
What is the content of the rename and merge files?

### ISSUE THREAD

**Issue by menzec** [yqyao/SSD_Pytorch#11]
how rename and merge some txt to"2012_test.txt, 2007_test.txt, 0712_trainval_test.txt, 2012_trainval.txt, 0712_trainval.txt"?What is the content of the every files?Can you show your file tree of data?

**Comment by yqyao** [comment]
2012_test.txt and 2007_test.txt mean VOC2007 test file and VOC2012 test file. 0712_trainval_test.txt means VOC2007 trainval  + VOC2012 trainval + VOC2007 test file. You can find the data in http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html  @menzec
