### ISSUE TITLE
refinedet

### ISSUE THREAD

**Issue by xingjici** [yqyao/SSD_Pytorch#13]
how to modify refinedet+resnet512？

**Comment by yqyao** [comment]
You can generate config base refine_vgg_voc_512.yaml and change the backbone. @xingjici

**Comment by rw1995** [comment]
我想使用您的代码运行refinedet 请问需要什么要求吗？因为新手 第一次跑代码？求指教，i need your help,please

**Comment by rw1995** [comment]
请问下师兄，关于您在帖子中写的数据合并是什么意思？我不是很明白
1.voc2012和voc2007中都在不同文件夹中都有一些jpg和png的图片，是将所有的图片都放在VOCROOT/VOC0712/JPEGImages中，还是将voc2007和2012的JPEGImages放在VOC0712/JPEGImages
2.重命名是如何写？我尝试了很多，但是真的让我很困惑？

真的是很抱歉屡次问您这么低级的问题，如何能帮到我，我将万分感谢您
@yqyao

**Comment by qq276399331** [comment]
@rw1995 就是将07和12的数据集照片放在一起，进行训练，然后你的标注文件也记得需要合并将07和12年的，重命名是什么意思，你将两个文件夹合在一起后conf 中给出了数据的一个命名你可以去看看
