### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by rw1995** [yqyao/SSD_Pytorch#16]
师兄，我有些问题需要您的帮助
在运行代码前，我做了以下的工作
1. sh make.sh ，将ssd_portch中nms文件夹中的长串名重命名cpu_nms.so和gup.nums.so,删除了sh文件中的两个mv，尽管我使用了anaconda虚拟环境，但是没有更改，因为没有出现问题
运行显示
$ sh make.shrunning build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
————————————————————————————————————————————
2.将demo.py中的cuda_device_version从“1，0”改为了0，这个保证了可以不显示cuda(38)错误
错误如下
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:70
————————————————————————————————————————————
3.将from data import import COCODectio.... 改为 from data.coco import COCODection 其他类似 
----------------------------------------------------------------------------------------------------------

但是我现在运行您的demo.py代码，出现了问题
(pytorch0.4.0) csy@csy:~/SSD_Pytorch$ python demo.py --cfg ./configs/ssd_vgg_voc.yaml --images ./images --save_folder ./output
Traceback (most recent call last):
  File "demo.py", line 173, in <module>
    main()
  File "demo.py", line 142, in main
    checkpoint = torch.load(args.weights)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'weights/ssd_darknet_300.pth'

我找不到ssd_darknet_300pth，我不知道这是如何产生的，我正在调整上面173.142的问题，应该是我的电脑配置不是一样导致的

望师兄指教，多谢了，这将是我第一个运行的代码，十分希望您能教教我

**Comment by qq276399331** [comment]
你可能没有训练过 ssd_darknet这个模型，

**Comment by yqyao** [comment]
ssd_darknet 是用的yolo的基础网络，需要自己训练 @rw1995

**Comment by yqyao** [comment]
这个问题我先关了，如果还有问题你可以重新打开 @rw1995
