### ISSUE TITLE
How to test voc 2012 or coco

### ISSUE THREAD

**Issue by qq276399331** [yqyao/SSD_Pytorch#22]

**Comment by yqyao** [comment]
you need produce the results file and test online in VOC http://host.robots.ox.ac.uk/pascal/VOC/voc2012/ @qq276399331

**Comment by qq276399331** [comment]
您的代码中好像没有对json文件的生成对么，

**Comment by yqyao** [comment]
有吧，在coco.py里面的290 行 @qq276399331

**Comment by qq276399331** [comment]
coco的代码有些问题，不能直接去测test数据集，我做了些修改要屏蔽掉transform，但是voc2012的我不知道怎么去修改您的代码

**Comment by yqyao** [comment]
voc 的那个我设置了标识符的，你好好阅读下代码，voc0712.py @qq276399331

**Comment by qq276399331** [comment]
您的意思是我重新弄命名么将2012test@yqyao
