### ISSUE TITLE
SSD参数问题

### ISSUE THREAD

**Issue by qq276399331** [yqyao/SSD_Pytorch#25]
作者您好，我最近发现您代码中，320尺寸大小的drf，最后steps为什么是300，不应该是320么

**Comment by yqyao** [comment]
最早的drf的尺寸是300，后来我改成了320了，估计那个地方我没改好 @qq276399331

**Comment by qq276399331** [comment]
@yqyao 谢谢您的及时回答，好像输入320的都错了，这对实验是否有影响。

**Comment by yqyao** [comment]
有一定的影响 @ @qq276399331 但是320好像我这边跑过，结果差不多

**Comment by qq276399331** [comment]
能提供下参数么，MinSIZE这些大小是不是也要相应的调整呢 @yqyao

**Comment by qq276399331** [comment]
能够提供下参数么，我感觉只是单一的修改后面step 107 320 么 ，minsize 和 maxsize也应该修改吧 @yqyao  
再次感谢您及时的回复

**Comment by yqyao** [comment]
我不太记得了 @qq276399331 这个好早之前跑得，但是从理论来看影响不大

**Comment by qq276399331** [comment]
我还发现代码中虽然是320的输入但是您的MAX_SIZE以及min_size尺寸都没有换

**Comment by yqyao** [comment]
哪个文件？ @qq276399331

**Comment by qq276399331** [comment]
@yqyao 比如说DRF 其中minsize和maxsize都是300的参数

**Comment by qq276399331** [comment]
@yqyao 我感觉这样是不是会造成一些误差，是否需要更改下参数以确保训练的正确性

**Comment by yqyao** [comment]
那个原始的就是300的输入，可能是input size 我最后填错了，影响应该不大 @qq276399331

**Comment by qq276399331** [comment]
但是我看DRF320的上面用的是40，同时RFB320您也是用的该参数

**Comment by yqyao** [comment]
影响不大的 @qq276399331

**Comment by qq276399331** [comment]
@yqyao  不会造成中心点偏移么

**Comment by yqyao** [comment]
我还是没懂你的意思，这个size 和中心点偏移有什么关系。。。这个不是anchor的最小size 和最大size嘛，中心点不还是那个位置嘛  @qq276399331

**Comment by qq276399331** [comment]
@yqyao 我的意思说整个参数假如输入改成320，如果不将参数进行更改，对SSD-Resnet影响不大么

**Comment by qq276399331** [comment]
@yqyao 我有个问题可以请教下您么，虽然map指标很高，但是可视化的效果并不好这是什么原因呢

**Comment by yqyao** [comment]
.哪个数据集？ @qq276399331 我这边VOC的可视化都还挺好的，你可以把pr曲线画一下

**Comment by qq276399331** [comment]
VOC2007test数据集，您有什么联系方式么，这个问题已经困扰我很久了。

**Comment by qq276399331** [comment]
我的邮箱是276399331@qq.com,这个问题困扰我很久了，希望你能帮助我，我重新写了个demo虽然出现了很多框但是效果还是看起来不如ssdvgg300好，可是在您代码上计算的map确比vgg要高很多

**Comment by yqyao** [comment]
个别图片不好吧，整体应该是有提升的 @qq276399331

**Comment by qq276399331** [comment]
@yqyao demo我不知道您是否更改过与DRFNet中，总感觉demo出来的效果不是很好，
