### ISSUE TITLE
我用了demo.py 提示维度问题

### ISSUE THREAD

**Issue by luvWY** [yqyao/SSD_Pytorch#26]
我采用了 refine_res101_voc-.yaml的配置文件 然后在训练时候保存的refine_res_epoch_210_300.pth
我eval是可以通过的，但是在demo.py时 `在im_dete的函数里面output = net(x)报错：
`The size of tensor a (19) must match the size of tensor b (20) at non-singleton dimension 3`

我不是很懂，我的模型和load的参数应该是匹配的，为什么会报错呢。
请教一下！

**Comment by luvWY** [comment]
好像是config里面的参数问题 INPUT_WH:设置成 320就可以跑通  但是和训练一样的300大小就不行 为什么

**Comment by yqyao** [comment]
refineDet 只能支持320的输入，64的倍数，因为那个反卷积的关系 @luvWY

**Comment by luvWY** [comment]
> refineDet 只能支持320的输入，64的倍数，因为那个反卷积的关系 @luvWY

了解了

**Comment by rw1995** [comment]
> > refineDet 只能支持320的输入，64的倍数，因为那个反卷积的关系 @luvWY
> 
> 了解了

请问下如何合并数据集，我已经困扰了2天了，求助 @luvWY ，main文件夹下的txt实在太多了
