### ISSUE TITLE
cannot import name 'namedtuple'

### ISSUE THREAD

**Issue by RichardHWD** [yqyao/SSD_Pytorch#29]
python build.py build_ext --inplace总是爆出 cannot import name 'namedtuple'，怎么回事啊老哥

**Comment by RichardHWD** [comment]
I solve this problem.Because you have create your own collections module in /utils.

**Comment by rw1995** [comment]
> I solve this problem.Because you have create your own collections module in /utils.
怎么解决的啊？有具体做法没

**Comment by rw1995** [comment]
解决了，做法就是删除ssd_pytorch项目中util文件夹下的collections.py文件就行
如果出现没有……36m……文件，就把 make.sh中关于mv……的两行代码注释掉就行，然后重新sh ./make.sh
