### ISSUE TITLE
Can not use optim.Adam

### ISSUE THREAD

**Issue by tuxiangshibie** [yqyao/SSD_Pytorch#30]
"  File "/data/tangkai/SSD_Pytorch/layers/modules/refine_multibox_loss.py", line 164, in forward
    targets_weighted = conf_t[(pos + neg).gt(0)]
RuntimeError: copy_if failed to synchronize: device-side assert triggered"
when I use  optim.Adam i always get this error.

**Comment by tuxiangshibie** [comment]
I made a mistake

**Comment by rw1995** [comment]
can you tell me how to cat all txt there ate too many txt and mass== ,please tell me how to do it?
