### ISSUE TITLE
I only got 78.8 mAP for RefineDet320 on voc2017 test 

### ISSUE THREAD

**Issue by yijingru** [yqyao/SSD_Pytorch#31]
Hi,

I retrained the RefineDet320 but only got 78.8 mAP on VOC2017 test dataset. I didn't change settings in the refine_vgg_voc.yaml file except for the batch size, which I used 99 for three GPU paralleling. Do you know why?

**Comment by yqyao** [comment]
99 maybe too large for voc dataset, you can try the original batch size of 32. @ @yijingru
