### ISSUE TITLE
About refinet results

### ISSUE THREAD

**Issue by qq276399331** [yqyao/SSD_Pytorch#6]
Do you have any results about refinet_res and refinet_voc?

**Comment by yqyao** [comment]
I have the results of refinenet_voc. Please read the readme @qq276399331

**Comment by qq276399331** [comment]
Thank you for your timely recovery. I have read the results you provided, but only the results of refinenet_vgg, I don't know if you have the result of refinenet_resnet.

**Comment by yqyao** [comment]
Sorry，the results are lost @qq276399331
