### ISSUE TITLE
RefineDet320能得到80.4%mAP？

### ISSUE THREAD

**Issue by luuuyi** [yqyao/SSD_Pytorch#8]

**Comment by luuuyi** [comment]
你好，你相对[lzx1413/PytorchSSD](https://github.com/lzx1413/PytorchSSD)改动了什么么？因为我感觉你应该是借鉴了这个repo，但是这个人的repo只能得到76左右的mAP。所以我比较好奇你是不是改动过了啥？

**Comment by yqyao** [comment]
我这个代码重构了好多次，应该是改了些东西，具体改了啥记不清了 @luuuyi
