### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by youtang1993** [yqyao/SSD_Pytorch#9]
非常感谢你的工作，我在运行train.py时遇到了一个小问题。如果注释掉第314~324行，也就是训练中不进行eval，代码会正常工作。但是如果保持原状，也即训练中进行eval的做法，程序无法进入下一个epoch继续训练，程序不会报错，也不会停止工作，但同时GPU的使用率也会降为0。请问如何解决？

**Comment by yqyao** [comment]
这个是multiprocess 的锅，我这边偶尔也会出现 @youtang1993
